### PR TITLE
Add unreachable hosts to runner results

### PR DESCRIPTION
**Pull request by jokurz**
In an automated environment it would be beneficial to get the unreachable hosts in case the flag `ignore_unreachable` is set to `True`. Due to that I propose to add the list of hosts to the `RunnersResult`.

### CODE REVIEW

**Comment by href** [comment]
That seems like a great idea. Do you mind adding a little test for it? There are already some unreachable tests in `test_api.py`, so this shouldn't result in more than a few lines of code. You can even extend an existing test if you like, for example `test_ignore_unreachable`.

Thank you!

**Comment by jokurz** [comment]
`test_ignore_unreachable` was executed with localhost. This has been fixed.

**Comment by href** [comment]
There still seems to be an issue: https://travis-ci.org/seantis/suitable/jobs/595589817

**Comment by href** [comment]
Nice, thanks!

**Pull request merged**
