### PR TITLE
feat: adds dict params support

### PR DESCRIPTION
**Pull request by Liuyanglong**
feat:  adds dict params support.

For example:
I want to use ios_command module to run command, the params is like:
```
{
    "commands":"show version",
    "provider":{
        "host":"10.x.x.x",
        "username":"uname",
        "password":"passwd",
        "authorize":False
    }
}
```

The Full use case is:

```python
#!/usr/local/python2.7/bin/python
from suitable import Api

hosts = Api(['127.0.0.1'],gather_facts="no",connection="local")
res = hosts.ios_command(  {"commands":'show version',"provider":{"host":"10.x.x.x","username":"uname","password":"passwd","authorize":False}} )
print res 
```

### CODE REVIEW

**Comment by Liuyanglong** [comment]
@href  What is the "codecov/patch — 50% of diff hit (target 99.66%)" mean?

**Comment by href** [comment]
I think it means how much of your code changes are actually covered by tests.

You've discovered a bigger issue here. Suitable doesn't deal with dictionaries or lists in arguments at all. I'm also afraid that your approach isn't quite right. Basically, this is how the command should look like:

```python
hosts.ios_command(commands='show version', 'provider': {
    "host":"10.x.x.x",
    "username":"uname",
    "password":"passwd",
    "authorize":False
})
```

Your approach only covers passing the whole thing as a dictionary, using non-keyword args. However, non-keyword args in Suitable are basically reserved for the command and shell module (just like in Ansible: `command: /sbin/setenforce 1`)

Interestingly enough your code works with passing a dictionary to the Ansible play. I remember that not working when I started Suitable. Since that works now however, we can easily support list and dictionary arguments. I've added this to https://github.com/seantis/suitable/commit/4dd95de5118c97806bc2f6560280219a78f39d74. Do you mind having a look at this commit to see if it works with your ios_command usage?

Also, thank you for bringing this to my attention!

**Comment by Liuyanglong** [comment]
@href  O yes, it works! Thank you~~

**Comment by href** [comment]
Sure thing :)

**Pull request closed without merging**
